### ISSUE TITLE
Error occurred while executing command for source

### ISSUE THREAD

**Issue by ghost** [sarhatabaot/Composer#14]
## **I'm using spongeforge on 1.12.2**
> [11:12:54] [Server thread/ERROR] [Sponge]: **Error occurred while executing command 'composer shuffle' for source** GCEntityPlayerMP['MrRagtime'/3018, l='world', x=-123.64, y=67.74, z=183.86]: Index: 0, Size: 0
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>         at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_312]
>         at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_312]
>         at se.walkercrou.composer.nbs.MusicPlayer.play(MusicPlayer.java:102) ~[MusicPlayer.class:?]
>         at se.walkercrou.composer.nbs.MusicPlayer.play(MusicPlayer.java:130) ~[MusicPlayer.class:?]
>         at se.walkercrou.composer.nbs.MusicPlayer.shuffle(MusicPlayer.java:174) ~[MusicPlayer.class:?]
>         at se.walkercrou.composer.cmd.ComposerCommands.shuffleTracks(ComposerCommands.java:157) ~[ComposerCommands.class:?]
>         at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2838-7.4.7]
>         at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.4.7]
>         at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.4.7]
>         at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.4.7]
>         at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
>         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
>         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
>         at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.4.7]
>         at net.minecraft.network.PacketThreadUtil$1.redirect$zlf000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:529) [h.class:?]
>         at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:331) [SpongeImplHooks.class:1.12.2-2838-7.4.7]
>         at net.minecraft.server.MinecraftServer.redirect$zjj000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>         at net.minecraft.server.MinecraftServe
r.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
>
> ### **Note that this also happens when executing "`play-once`" and "`play`"**
>
> ## - [Log file](https://github.com/sarhatabaot/Composer/files/10047840/latest.log)

**Comment by ghost** [comment]
I'm currently using version **[4.1.1](https://github.com/sarhatabaot/Composer/releases/tag/4.1.1)**

**Comment by sarhatabaot** [comment]
It seems to me no songs are loaded for some reason. Can you zip your default playlist folder or all your tracks and send it here? Or to me on discord via sarhatabaot#0428

**Comment by ghost** [comment]
**Here**
- **[playlist.zip](https://github.com/sarhatabaot/Composer/files/10049032/playlist.zip)**

**Comment by ghost** [comment]
I just checked the README and I've noticed that I did not create a **playlist**  in "**config/composer/playlists**" and I didn't set "**use-playlist=**" to **true**. Could this be the problem?

**Comment by ghost** [comment]
Closing as not planned since I currently am not using sponge anymore plus I have had this issue opened for 25+ days.
@sarhatabaot, I know you're busy with other projects so please comment once you're available.

**Comment by sarhatabaot** [comment]
Hey! Sorry for inactivity. 

I'll try and have a look again on Monday evening.

**Comment by ghost** [comment]
I understand if you can not fix this issue by today.

**Comment by sarhatabaot** [comment]
Sorry, I haven't had time to work on this. Hoping I can work on this Thursday / Wednesday, sorry for the delay.

**Comment by ghost** [comment]
You're fine and like I said, I understand that you're busy with other projects.

**Comment by sarhatabaot** [comment]
> You're fine and like I said, I understand that you're busy with other projects.

Can you try using the latest pre-release: https://github.com/sarhatabaot/Composer/releases/tag/4.1.4-pre1 ?

**Comment by ghost** [comment]
I can try at around 7 PM PST

**Comment by ghost** [comment]
Sorry for keeping you waiting. Either me or my brother **[@Kiwifruit](https://github.com/KiwifruitDev)** will take a look at this when we can later today.

**Comment by ghost** [comment]
Very sorry for keeping you waiting. I'm closing this as incomplete because it has already been 3 weeks and I don't think I will have time to start up a sponge server *with* all of my sponge & forge mods I used when I made this issue.
I'm so sorry for the delay and not helping you out with this issue,
