### ISSUE TITLE
Songs not playing at the right pace... only first few notes

### ISSUE THREAD

**Issue by GavBog** [sarhatabaot/Composer#7]
Only a few notes are coming though the server. Could this be lagg related? I am running this server off a old pc settup so It could be a problem on my end too. Could you help me fix this?

**Comment by sarhatabaot** [comment]
Could you send the .nbs files you're using?
Also include what version of Sponge + Composer you're running.

**Comment by sarhatabaot** [comment]
Closed for not enough information.. I could not reproduce this.
