### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by Jean-Marc-H** [sarhatabaot/Composer#9]
Seems like when I try running one of the files I made in my list, I get an error related to my header. Here's the file:
[MilasDivineProtection.zip](https://github.com/sarhatabaot/Composer/files/3999285/MilasDivineProtection.zip)

**Comment by sarhatabaot** [comment]
Composer currently only supports the old NBS format. I'll update it to support the new format once sponge 1.14+ is out.

**Comment by DrZoddiak** [comment]
I should have mentioned this, but this is fixed with https://github.com/sarhatabaot/Composer/commit/d0e6b57fcca52ac5a41c4658cb2b624ff36988d5

**Comment by sarhatabaot** [comment]
Fixed in  https://github.com/sarhatabaot/Composer/commit/d0e6b57fcca52ac5a41c4658cb2b624ff36988d5
Thank @DrZoddiak for the pr!
